name: self-host-arm64-build
on:
  workflow_dispatch:
    inputs:
      package:
        description: 'package name'
        required: true
        default: 'lsphp83'
        type: choice
        options:
          - lsphp83
          - lsphp83-apcu
          - lsphp83-imagick
          - lsphp83-ioncube
          - lsphp83-memcached
          - lsphp83-msqpack
          - lsphp83-pear
          - lsphp83-redis
      version:
        description: 'version number'
        required: true
        type: number
      revision:
        description: 'revision number'
        required: true
        type: number        
      distro:
        description: 'distro'
        required: true
        default: 'noble'
        type: choice
        options:
          - noble
          - jammy
          - bookworm
          - bullseye
      arch:
        description: 'arch'
        required: true
        default: 'arm64'
        type: choice
        options:
          - amd64
          - arm64

jobs:
  package:
    runs-on: self-hosted
    container:
      image: eggcold/debian-build
      options: --user root --cap-add SYS_ADMIN --security-opt seccomp=unconfined --security-opt apparmor=unconfined
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          ls -al
          pwd
          uname -m
          cp /root/.pbuilderrc $HOME/
          bash build.sh ${{ inputs.package }} ${{ inputs.version }} ${{ inputs.revision }} ${{ inputs.distro }} ${{ inputs.arch }}
